import 'package:flutter/material.dart';

class name extends StatefulWidget {
  const name({super.key});

  @override
  State<name> createState() => _nameState();
}

class _nameState extends State<name> {
  List<String> list = [
    '1	الرَّحْمَنُ	AR-RAHMAAN \n	The Beneficent',
    '2	الرَّحِيمُ	AR-RAHEEM\n	The Merciful',
    '3	الْمَلِكُ	AL-MALIK	\n The King',
    '4	الْقُدُّوسُ	AL-QUDDUS\n	The Most Sacred',
    '5	السَّلاَمُ	AS-SALAM	\nThe Source of Peace, The Flawless',
    '6	الْمُؤْمِنُ	AL-MU’MIN\n	The Infuser of Faith',
    '7	الْمُهَيْمِنُ	AL-MUHAYMIN	\nThe Preserver of Safety',
    '8	الْعَزِيزُ	AL-AZIZ\n	All Mighty',
    '9	الْجَبَّارُ	AL-JABBAR	\nThe Compeller, The Restorer',
    '10	ُالْمُتَكَبِّر	AL-MUTAKABBIR\n	The Supreme, The Majestic',
    '11	الْخَالِقُ	AL-KHAALIQ	\nThe Creator, The Maker',
    '12	الْبَارِئُ	AL-BAARI	\nThe Evolver',
    '13	الْمُصَوِّرُ	AL-MUSAWWIR	\nThe Fashioner',
    '14	الْغَفَّارُ	AL-GHAFFAR	\nThe Great Forgiver',
    '15	الْقَهَّارُ	AL-QAHHAR	\nThe All-Prevailing One',
    '16	الْوَهَّابُ	AL-WAHHAAB\n	The Supreme Bestower',
    '17	الرَّزَّاقُ	AR-RAZZAAQ	\nThe Provider',
    '18	الْفَتَّاحُ	AL-FATTAAH\n	The Supreme Solver',
    '19	اَلْعَلِيْمُ	AL-‘ALEEM\n	The All-Knowing',
    '20	الْقَابِضُ	AL-QAABID\n	The Withholder',
    '21	الْبَاسِطُ	AL-BAASIT	\nThe Extender',
    '22	الْخَافِضُ	AL-KHAAFIDH	\nThe Reducer',
    '23	الرَّافِعُ	AR-RAAFI’\n	The Exalter, The Elevator',
    '24	الْمُعِزُّ	AL-MU’IZZ\n	The Honourer, The Bestower',
    '25	ٱلْمُذِلُّ	AL-MUZIL\n	The Dishonourer, The Humiliator',
    '26	السَّمِيعُ	AS-SAMEE’	\nThe All-Hearing',
    '27	الْبَصِيرُ	AL-BASEER\n	The All-Seeing',
    '28	الْحَكَمُ	AL-HAKAM\n	The Impartial Judge',
    '29	الْعَدْلُ	AL-‘ADL\n	The Utterly Just',
    '30	اللَّطِيفُ	AL-LATEEF\n	The Subtle One, The Most Gentle',
    '31	الْخَبِيرُ	AL-KHABEER\n	The All-Aware',
    '32	الْحَلِيمُ	AL-HALEEM\n	The Most Forbearing',
    '33	الْعَظِيمُ	AL-‘AZEEM\n	The Magnificent, The Supreme',
    '34	الْغَفُور	AL-GHAFOOR\n	The Great Forgiver',
    '35	الشَّكُورُ	ASH-SHAKOOR	\nThe Most Appreciative',
    '36	الْعَلِيُّ	AL-‘ALEE	\nThe Most High, The Exalted',
    '37	الْكَبِيرُ	AL-KABEER	\nThe Most Great',
    '38	الْحَفِيظُ	AL-HAFEEDH\n	The Preserver',
    '39	المُقيِت	AL-MUQEET\n	The Sustainer',
    '40	اﻟْﺣَسِيبُ	AL-HASEEB	\nThe Reckoner',
    '41	الْجَلِيلُ	AL-JALEEL	\nThe Majestic',
    '42	الْكَرِيمُ	AL-KAREEM	\nThe Most Generous, The Most Esteemed',
    '43	الرَّقِيبُ	AR-RAQEEB	\nThe Watchful',
    '44	ٱلْمُجِيبُ	AL-MUJEEB	\nThe Responsive One',
    '45	الْوَاسِعُ	AL-WAASI’	\nThe All-Encompassing, the Boundless',
    '46	الْحَكِيمُ	AL-HAKEEM	\nThe All-Wise',
    '47	الْوَدُودُ	AL-WADUD	\nThe Most Loving',
    '48	الْمَجِيدُ	AL-MAJEED\n	The Glorious, The Most Honorable',
    '49	الْبَاعِثُ	AL-BA’ITH\n	The Infuser of New Life',
    '50	الشَّهِيدُ	ASH-SHAHEED	\nThe All Observing Witnessing',
    '51	الْحَقُ	AL-HAQQ	\nThe Absolute Truth',
    '52	الْوَكِيلُ	AL-WAKEEL	\nThe Trustee, The Disposer of Affairs',
    '53	الْقَوِيُ	AL-QAWIYY	\nThe All-Strong',
    '54	الْمَتِينُ	AL-MATEEN	\nThe Firm, The Steadfast',
    '55	الْوَلِيُّ	AL-WALIYY	\nThe Protecting Associate',
    '56	الْحَمِيدُ	AL-HAMEED	\nThe Praiseworthy',
    '57	الْمُحْصِي	AL-MUHSEE\n	The All-Enumerating, The Counter',
    '58	الْمُبْدِئُ	AL-MUBDI\n	The Originator, The Initiator',
    '59	ٱلْمُعِيدُ	AL-MUEED\n	The Restorer, The Reinstater',
    '60	الْمُحْيِي	AL-MUHYI	\nThe Giver of Life',
    '61	اَلْمُمِيتُ	AL-MUMEET\n	The Creator of Death',
    '62	الْحَيُّ	AL-HAYY	\nThe Ever-Living',
    '63	الْقَيُّومُ	AL-QAYYOOM\n	The Sustainer, The Self-Subsisting',
    '64	الْوَاجِدُ	AL-WAAJID\n	The Perceiver',
    '65	الْمَاجِدُ	AL-MAAJID	\nThe Illustrious, the Magnificent',
    '66	الْواحِدُ	AL-WAAHID\n	The One',
    '67	اَلاَحَدُ	AL-AHAD\n	The Unique, The Only One',
    '68	الصَّمَدُ	AS-SAMAD	\nThe Eternal, Satisfier of Needs',
    '69	الْقَادِرُ	AL-QADEER\n	The Omnipotent One',
    '70	الْمُقْتَدِرُ	AL-MUQTADIR\n	The Powerful',
    '71	الْمُقَدِّمُ	AL-MUQADDIM\n	The Expediter, The Promoter',
    '72	الْمُؤَخِّرُ	AL-MU’AKHKHIR	\nThe Delayer',
    '73	الأوَّلُ	AL-AWWAL\n	The First',
    '74	الآخِرُ	AL-AAKHIR\n	The Last',
    '75	الظَّاهِرُ	AZ-ZAAHIR\n	The Manifest',
    '76	الْبَاطِنُ	AL-BAATIN\n	The Hidden One, Knower of the Hidden',
    '77	الْوَالِي	AL-WAALI	\nThe Sole Governor',
    '78	الْمُتَعَالِي	AL-MUTA’ALI	\nThe Self Exalted',
    '79	الْبَرُّ	AL-BARR\n	The Source of All Goodness',
    '80	التَّوَابُ	AT-TAWWAB	\nThe Ever-Pardoning, The Relenting',
    '81	الْمُنْتَقِمُ	AL-MUNTAQIM	\nThe Avenger',
    '82	العَفُوُ	AL-‘AFUWW	\nThe Pardoner',
    '83	الرَّؤُوفُ	AR-RA’OOF\n	The Most Kind',
    '84	َمَالِكُ ٱلْمُلْكُ	MAALIK-UL-MULK	\nMaster of the Kingdom, Owner of the Dominion',
    '85	ذُوالْجَلاَلِ وَالإكْرَامِ	DHUL-JALAALI WAL-IKRAAM	Lord of Glory and Honour,\n Lord of Majesty and Generosity',
    '86	الْمُقْسِطُ	AL-MUQSIT\n	The Just One',
    '87	الْجَامِعُ	AL-JAAMI’	\nThe Gatherer, the Uniter',
    '88	ٱلْغَنيُّ	AL-GHANIYY	\nThe Self-Sufficient, The Wealthy',
    '89	ٱلْمُغْنِيُّ	AL-MUGHNI	\nThe Enricher',
    '90	 اَلْمَانِعُ	AL-MANI’\n	The Withholder',
    '91	 الضَّارَ	AD-DHARR	\nThe Distresser',
    '92	 النَّافِعُ	AN-NAFI’\n	The Propitious, the Benefactor',
    '93	 النُّورُ	AN-NUR	\nThe Light, The Illuminator',
    '94	 الْهَادِي	AL-HAADI	\nThe Guide',
    '95	 الْبَدِيعُ	AL-BADEE’\n	The Incomparable Originator',
    '96	 اَلْبَاقِي	AL-BAAQI	\nThe Everlasting',
    '97	 الْوَارِثُ	AL-WAARITH\n	The Inheritor, The Heir',
    '98	 الرَّشِيدُ	AR-RASHEED\n	The Guide, Infallible Teacher',
    '99	 الصَّبُورُ	AS-SABOOR	\nThe Forbearing, The Patient',
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('اسماء الله الحسنى')),
        body: ListView.builder(
          itemCount: list.length,
          itemBuilder: (context, index) => Container(
              padding: EdgeInsets.all(8),
              margin: EdgeInsets.all(10),
              decoration: BoxDecoration(
                  color: Color.fromARGB(255, 224, 224, 224),
                  borderRadius: BorderRadius.all(Radius.circular(15))),
              child: Text(
                list[index],
                textAlign: TextAlign.start,
                style: TextStyle(
                    letterSpacing: 0.8,
                    color: Colors.black,
                    fontWeight: FontWeight.bold,
                    fontSize: 20),
              )),
        ));
  }
}
